version: '2'

services:
  micrometerpoc:
    image: micrometerpoc:latest
    environment:
      - SPRING_APPLICATION_NAME=micrometerPOC
      - SPRING_ZIPKIN_BASE_URL=http://zipkin:9411/
      - SPRING_ZIPKIN_ENABLED=true
      - SERVER_PORT=8080
    ports:
      - "8080:8080"

  zipkin:
    image: openzipkin/zipkin
    ports:
      - "9411:9411"